export type ChatEntry = {
  id: string;
  keywords: string[];
  answerFr: string;
  answerEn: string;
  answerAr: string;
  answerDarija: string;
};

export const chatKnowledgeBase: ChatEntry[] = [
  {
    id: "identity",
    keywords: ["qui", "who", "chrourou", "achrourou", "identite", "identity", "من", "هو", "اشرورو", "شرورو", "هوية", "شكون", "shkoun", "chkoun", "houwa", "hiya"],
    answerFr: "Mohamed Chrourou (محمد أشرورو) est membre de la Chambre des Représentants du Maroc, président de la commune d'Oulmès, et membre du Parti Authenticité et Modernité (PAM).",
    answerEn: "Mohamed Chrourou is a Member of the Moroccan House of Representatives, President of the Oulmès commune, and a member of the Party of Authenticity and Modernity (PAM).",
    answerAr: "محمد أشرورو عضو في مجلس النواب المغربي، رئيس جماعة أولماس، وعضو في حزب الأصالة والمعاصرة (PAM).",
    answerDarija: "محمد أشرورو هو عضو فمجلس النواب ديال المغرب، رئيس جماعة أولماس، وعضو فحزب الأصالة والمعاصرة (PAM).",
  },
  {
    id: "party",
    keywords: ["parti", "party", "pam", "authenticite", "modernite", "حزب", "الأصالة", "المعاصرة", "بام", "hizb", "lhizb", "chi3b"],
    answerFr: "Il est membre du Parti Authenticité et Modernité (PAM). Site officiel : https://pam.ma/",
    answerEn: "He is a member of the Party of Authenticity and Modernity (PAM). Official site: https://pam.ma/",
    answerAr: "هو عضو في حزب الأصالة والمعاصرة (PAM). الموقع الرسمي: https://pam.ma/",
    answerDarija: "هو عضو فحزب الأصالة والمعاصرة (PAM). السيت ديالهم: https://pam.ma/",
  },
  {
    id: "constituency",
    keywords: ["circonscription", "constituency", "khemisset", "oulmes", "region", "الخميسات", "أولماس", "دائرة", "جهة", "da2ira", "daira", "khmisset"],
    answerFr: "Il représente la circonscription de Khémisset – Oulmès à la Chambre des Représentants.",
    answerEn: "He represents the Khémisset – Oulmès constituency in the House of Representatives.",
    answerAr: "يمثل الدائرة الانتخابية الخميسات – أولماس في مجلس النواب.",
    answerDarija: "كيمثل الدائرة ديال الخميسات – أولماس فمجلس النواب.",
  },
  {
    id: "mandate",
    keywords: ["mandat", "legislature", "2021", "2026", "elu", "elected", "ولاية", "منتخب", "تشريعية", "wilaya", "mountakhab"],
    answerFr: "Il est membre de la Chambre des Représentants pour la législature 2021–2026.",
    answerEn: "He has been a Member of the House of Representatives for the 2021–2026 legislature.",
    answerAr: "هو عضو في مجلس النواب للولاية التشريعية 2021–2026.",
    answerDarija: "هو عضو فمجلس النواب للولاية ديال 2021–2026.",
  },
  {
    id: "commune",
    keywords: ["commune", "president de la commune", "oulmes president", "maire", "جماعة", "رئيس الجماعة", "رئيس جماعة", "jamaa", "jama3a", "ra2is"],
    answerFr: "Il est président de la commune d'Oulmès (statut à vérifier officiellement).",
    answerEn: "He is President of the Oulmès commune (status pending official verification).",
    answerAr: "هو رئيس جماعة أولماس (الوضع في طور التحقق الرسمي).",
    answerDarija: "هو رئيس جماعة أولماس (بصح هاد المعلومة مازال كيتأكد منها رسميا).",
  },
  {
    id: "cattle-federation",
    keywords: ["elevage", "bovin", "cattle", "federation", "zaer", "تربية", "أبقار", "فيدرالية", "زعير", "zaar", "baqar"],
    answerFr: "En 2019, il a présidé la fédération nationale associée aux éleveurs de bovins Oulmès-Zaër.",
    answerEn: "In 2019, he presided over the national federation associated with Oulmès-Zaër cattle breeders.",
    answerAr: "في 2019، ترأس الفيدرالية الوطنية المرتبطة بمربي الأبقار في أولماس-زعير.",
    answerDarija: "في 2019، كان رئيس الفيدرالية الوطنية ديال مربي البقر ف أولماس-زعير.",
  },
  {
    id: "surveying",
    keywords: ["geometre", "topographe", "surveying", "ingenieur", "engineer", "مهندس", "طبوغرافي", "مساح", "mouhandis"],
    answerFr: "De 2012 à 2015, il a présidé le Conseil national de l'Ordre des ingénieurs géomètres-topographes.",
    answerEn: "From 2012 to 2015, he was President of the National Council of Surveying Engineers.",
    answerAr: "من 2012 إلى 2015، ترأس المجلس الوطني لهيئة المهندسين المساحين الطبوغرافيين.",
    answerDarija: "من 2012 لـ2015، كان رئيس المجلس الوطني ديال المهندسين المساحين الطبوغرافيين.",
  },
  {
    id: "pam-leadership",
    keywords: ["groupe parlementaire", "parliamentary group", "secretaire provincial", "provincial secretary", "فريق برلماني", "كاتب إقليمي", "katib iqlimi"],
    answerFr: "En 2017, son élection à la présidence du groupe parlementaire PAM a été rapportée. En 2022, il a été élu secrétaire provincial du PAM à Khémisset.",
    answerEn: "In 2017, his election as president of the PAM parliamentary group was reported. In 2022, he was elected PAM provincial secretary for Khémisset.",
    answerAr: "في 2017، تم تناقل خبر انتخابه رئيسا للفريق البرلماني لحزب PAM. وفي 2022، انتُخب كاتبا إقليميا للحزب بالخميسات.",
    answerDarija: "في 2017، تقال بلي تنتخب رئيس الفريق البرلماني ديال PAM. وفي 2022، تنتخب كاتب إقليمي ديال الحزب فالخميسات.",
  },
  {
    id: "2026-candidate",
    keywords: ["candidat", "candidate", "election 2026", "2026", "مرشح", "انتخابات", "mourachah", "intikhabat"],
    answerFr: "Il est candidat du PAM pour la circonscription de Khémisset–Oulmès en 2026.",
    answerEn: "He is the PAM candidate for the Khémisset–Oulmès constituency in 2026.",
    answerAr: "هو مرشح حزب PAM عن دائرة الخميسات–أولماس لانتخابات 2026.",
    answerDarija: "هو مرشح ديال PAM على الدائرة ديال الخميسات–أولماس فانتخابات 2026.",
  },
  {
    id: "ecological-baths",
    keywords: ["bains", "baths", "ecologique", "ecological", "climat", "climate", "projet", "project", "حمامات", "بيئية", "مناخ", "مشروع", "hammamat", "machrou3", "mounakh"],
    answerFr: "Le projet des Bains écologiques d'Oulmès a été développé par la commune avec l'Association Ingénierie et Développement et la Coalition marocaine des collectivités territoriales pour le climat. Il a reçu le Prix international des maires pour le climat (Paris, septembre 2022).",
    answerEn: "The Ecological Oulmès Baths project was developed by the commune with the Association Ingénierie et Développement and the Moroccan Coalition for Territorial Communities for Climate. It received the International Climate Mayors Award (Paris, September 2022).",
    answerAr: "مشروع الحمامات البيئية بأولماس طورته الجماعة بشراكة مع جمعية الهندسة والتنمية والائتلاف المغربي للجماعات الترابية من أجل المناخ. حصل على الجائزة الدولية لرؤساء الجماعات من أجل المناخ (باريس، شتنبر 2022).",
    answerDarija: "مشروع الحمامات البيئية ديال أولماس دارتو الجماعة مع جمعية الهندسة والتنمية والائتلاف المغربي للجماعات الترابية للمناخ. خدا الجائزة الدولية لرؤساء الجماعات على المناخ (باريس، شتنبر 2022).",
  },
  {
    id: "parliament-questions",
    keywords: ["question", "questions", "parlement", "parliament", "route", "road", "infrastructure", "سؤال", "أسئلة", "برلمان", "طريق", "sou2al", "berlamane", "tri9"],
    answerFr: "Il a soumis plusieurs questions parlementaires, notamment sur la route régionale 704 (Oulmès–Aklimous) et la route provinciale 4316 (Aït Aïko–Houdrane), toutes deux liées au ministère de l'Équipement et de l'Eau.",
    answerEn: "He has submitted several parliamentary questions, including on Regional Road 704 (Oulmès–Aklimous) and Provincial Road 4316 (Aït Aïko–Houdrane), both addressed to the Ministry of Equipment and Water.",
    answerAr: "تقدم بعدة أسئلة برلمانية، منها الطريق الجهوية 704 (أولماس–أكليموس) والطريق الإقليمية 4316 (آيت أيكو–هودران)، وكلاهما موجه لوزارة التجهيز والماء.",
    answerDarija: "دار بزاف ديال الأسئلة البرلمانية، من بينهم الطريق الجهوية 704 (أولماس–أكليموس) والطريق الإقليمية 4316 (آيت أيكو–هودران)، وجهين لوزارة التجهيز والماء.",
  },
  {
    id: "transport",
    keywords: ["transport", "chemin de fer", "railway", "gare", "4325", "circulation", "سكة", "قطار", "محطة", "sika", "9itar"],
    answerFr: "Le volet Transport & Infrastructure couvre la route régionale 704, les routes provinciales 4316 et 4325, les routes rurales, la sécurité routière et le projet de connexion ferroviaire à Khémisset.",
    answerEn: "The Transport & Infrastructure section covers Regional Road 704, Provincial Roads 4316 and 4325, rural roads, road safety, and the rail connection project to Khémisset.",
    answerAr: "محور النقل والبنية التحتية يشمل الطريق الجهوية 704، الطرق الإقليمية 4316 و4325، الطرق القروية، السلامة الطرقية، ومشروع الربط السككي بالخميسات.",
    answerDarija: "محور النقل والبنية التحتية فيه الطريق الجهوية 704، الطرق الإقليمية 4316 و4325، الطرق القروية، السلامة ديال الطريق، ومشروع الربط بالسكة الحديدية للخميسات.",
  },
  {
    id: "water-environment",
    keywords: ["eau", "water", "environnement", "environment", "durabilite", "sustainability", "ماء", "بيئة", "استدامة", "lma", "bi2a"],
    answerFr: "Le volet Eau & Environnement couvre l'accès à l'eau, les infrastructures hydrauliques, la conservation environnementale et la durabilité du territoire d'Oulmès.",
    answerEn: "The Water & Environment section covers access to water, water infrastructure, environmental conservation, and sustainability across the Oulmès territory.",
    answerAr: "محور الماء والبيئة يشمل الولوج إلى الماء، البنية التحتية المائية، الحفاظ على البيئة، واستدامة تراب أولماس.",
    answerDarija: "محور الماء والبيئة فيه الوصول للماء، البنية التحتية ديال الماء، المحافظة على البيئة، والاستدامة فتراب أولماس.",
  },
  {
    id: "agriculture",
    keywords: ["agriculture", "terre", "land", "eleveurs", "farmers", "patrimoine", "heritage", "فلاحة", "أرض", "مزارعين", "تراث", "falaha", "lard"],
    answerFr: "Le volet Territoire & Agriculture porte sur la terre, les éleveurs, la filière Oulmès-Zaër, l'économie locale et le patrimoine agricole.",
    answerEn: "The Territory & Agriculture section covers land, farmers, the Oulmès-Zaër sector, the local economy, and agricultural heritage.",
    answerAr: "محور التراب والفلاحة يتناول الأرض، المزارعين، قطاع أولماس-زعير، الاقتصاد المحلي، والتراث الفلاحي.",
    answerDarija: "محور التراب والفلاحة كيهضر على الأرض، الفلاحة، قطاع أولماس-زعير، الاقتصاد المحلي، والتراث الفلاحي.",
  },
  {
    id: "education",
    keywords: ["education", "ecole", "school", "jeunesse", "youth", "etudiant", "student", "bourse", "scholarship", "تعليم", "مدرسة", "شباب", "منحة", "ta3lim", "chabab"],
    answerFr: "Le volet Éducation & Jeunesse couvre l'éducation, la formation, le soutien étudiant et les initiatives jeunesse.",
    answerEn: "The Education & Youth section covers education, training, student support, and youth initiatives.",
    answerAr: "محور التعليم والشباب يشمل التعليم، التكوين، الدعم الطلابي، ومبادرات الشباب.",
    answerDarija: "محور التعليم والشباب فيه التعليم، التكوين، الدعم ديال الطلبة، ومبادرات الشباب.",
  },
  {
    id: "health",
    keywords: ["sante", "health", "clinique", "clinic", "hopital", "hospital", "campagne medicale", "medical campaign", "صحة", "عيادة", "مستشفى", "حملة طبية", "sa7a", "chi7a"],
    answerFr: "Le volet Santé couvre les campagnes médicales, les cliniques, les équipes médicales et les centres de santé dans la région.",
    answerEn: "The Health section covers medical campaigns, clinics, medical teams, and health centers in the region.",
    answerAr: "محور الصحة يشمل الحملات الطبية، العيادات، الأطقم الطبية، والمراكز الصحية بالجهة.",
    answerDarija: "محور الصحة فيه الحملات الطبية، العيادات، الأطقم الطبية، والمراكز الصحية فالجهة.",
  },
  {
    id: "culture",
    keywords: ["culture", "identite", "identity", "amazigh", "amazighe", "patrimoine culturel", "festival", "ثقافة", "أمازيغي", "مهرجان", "taqafa"],
    answerFr: "Le volet Culture & Identité met en avant la culture amazighe, le patrimoine local et les festivals du territoire d'Oulmès.",
    answerEn: "The Culture & Identity section highlights Amazigh culture, local heritage, and festivals in the Oulmès territory.",
    answerAr: "محور الثقافة والهوية يبرز الثقافة الأمازيغية، التراث المحلي، والمهرجانات في تراب أولماس.",
    answerDarija: "محور الثقافة والهوية كيبرز الثقافة الأمازيغية، التراث المحلي، والمهرجانات فتراب أولماس.",
  },
  {
    id: "transparency",
    keywords: ["transparence", "transparency", "registre public", "public record", "verifiable", "شفافية", "سجل عام"],
    answerFr: "Ce site vise à donner une vue transparente, sourcée et vérifiable du parcours et de l'activité de Mohamed Chrourou : biographie, parcours politique, activité parlementaire, projets, sources.",
    answerEn: "This site aims to give a transparent, sourced, and verifiable view of Mohamed Chrourou's career and activity: biography, political path, parliamentary activity, projects, sources.",
    answerAr: "يهدف هذا الموقع إلى تقديم رؤية شفافة وموثقة وقابلة للتحقق حول مسار محمد أشرورو ونشاطه: السيرة الذاتية، المسار السياسي، النشاط البرلماني، المشاريع، المصادر.",
    answerDarija: "هاد السيت الهدف ديالو يعطي صورة شفافة وموثقة على مسار محمد أشرورو: السيرة الذاتية، المسار السياسي، النشاط البرلماني، المشاريع، المصادر.",
  },
  {
    id: "media",
    keywords: ["media", "presse", "press", "interview", "controverse", "controversy", "couverture", "coverage", "إعلام", "صحافة", "مقابلة", "جدل"],
    answerFr: "La page Média distingue les allégations et litiges rapportés dans la presse des faits établis et sourcés.",
    answerEn: "The Media page distinguishes press-reported allegations and disputes from established, sourced facts.",
    answerAr: "صفحة الإعلام تميز بين الادعاءات والنزاعات التي تناقلتها الصحافة والحقائق الثابتة والموثقة.",
    answerDarija: "صفحة الإعلام كتفرق بين الادعاءات والخلافات اللي هضرات عليهم الصحافة والحقائق الثابتة والموثقة.",
  },
  {
    id: "sources",
    keywords: ["source", "sources", "verification", "verifie", "verified", "preuve", "proof", "مصادر", "مصدر", "تحقق", "دليل"],
    answerFr: "Toutes les informations proviennent de sources officielles : Chambre des Représentants, PAM, et le site de la commune d'Oulmès. Voir la page Sources pour le détail.",
    answerEn: "All information comes from official sources: the House of Representatives, PAM, and the Oulmès commune website. See the Sources page for details.",
    answerAr: "كل المعلومات مستقاة من مصادر رسمية: مجلس النواب، حزب PAM، وموقع جماعة أولماس. راجع صفحة المصادر للتفاصيل.",
    answerDarija: "كلشي المعلومات جايين من مصادر رسمية: مجلس النواب، حزب PAM، وسيت ديال جماعة أولماس. شوف صفحة المصادر باش تعرف الديتاي.",
  },
  {
    id: "contact",
    keywords: ["contact", "email", "joindre", "reach", "تواصل", "إيميل", "بريد", "twassol"],
    answerFr: "Vous pouvez le contacter via pamoulmes@gmail.com.",
    answerEn: "You can reach him at pamoulmes@gmail.com.",
    answerAr: "يمكنكم التواصل معه عبر pamoulmes@gmail.com.",
    answerDarija: "تقدر تتواصل معاه فهاد الإيميل: pamoulmes@gmail.com.",
  },
  {
    id: "default",
    keywords: [],
    answerFr: "Je n'ai pas d'information précise sur ce sujet. Essayez : parti, circonscription, mandat, commune, projets, transport, eau, agriculture, éducation, santé, culture, sources, contact.",
    answerEn: "I don't have specific information on that. Try: party, constituency, mandate, commune, projects, transport, water, agriculture, education, health, culture, sources, contact.",
    answerAr: "ليست لدي معلومة دقيقة حول هذا الموضوع. جرب: الحزب، الدائرة، الولاية، الجماعة، المشاريع، النقل، الماء، الفلاحة، التعليم، الصحة، الثقافة، المصادر، التواصل.",
    answerDarija: "ماعنديش معلومة دقيقة على هاد الموضوع. جرب: الحزب، الدائرة، الولاية، الجماعة، المشاريع، النقل، الماء، الفلاحة، التعليم، الصحة، الثقافة، المصادر، التواصل.",
  },
];
